
package zawgyitowininnwa;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

// For *.docx Docunments
import org.apache.poi.xwpf.extractor.XWPFWordExtractor;
import org.apache.poi.xwpf.usermodel.XWPFDocument;

// For *.doc Docunments
import org.apache.poi.hwpf.HWPFDocument;
import org.apache.poi.hwpf.extractor.WordExtractor;

/**

 @author Kiwi


 */
public class ZawgyiToWinInnwaGUI extends JFrame
{

    // Properties 
    ZawgyiToUnicode zwToUnicode = new ZawgyiToUnicode(); 
    WinInnwaToUnicode winToUnicode = new WinInnwaToUnicode();
    WinInnwaToZawgyi winInnwaToZawgyi = new WinInnwaToZawgyi();
    
    JFileChooser fileChooser = new JFileChooser ();
    ZawgyiToWinInnwa zwToInnwa = new ZawgyiToWinInnwa(); 
    //TestClass zwToInnwa = new TestClass(); 
    
    /**
     Creates new form ZawgyiToWinInnwaGUI
     */
    public ZawgyiToWinInnwaGUI ()
    {
        initComponents();
    }
    
    public ZawgyiToWinInnwaGUI (String words)
    {
        initComponents();
        
        ZawgyiJTextArea.setText(words);
    }

    /**
     This method is called from within the constructor to initialize the form.
     WARNING: Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        zawgyiToWinInnwaJButton = new javax.swing.JButton();
        winInnWaToZawgyiJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MessageForMS_WordJTextArea = new javax.swing.JTextArea();
        copyRightJLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        WinInnwaJTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        ZawgyiJTextArea = new javax.swing.JTextArea();
        winInnwaToZawgyiTextAreaJButton = new javax.swing.JButton();
        enterZawgyiFontJLabel = new javax.swing.JLabel();
        zawgyiToWinInnwaTextAreaJButton = new javax.swing.JButton();
        enterWinInnwaJLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        zawgyiToWinInnwaJButton.setText("Zawgyi File >> Win Innwa");
        zawgyiToWinInnwaJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                zawgyiToWinInnwaJButtonActionPerformed(evt);
            }
        });

        winInnWaToZawgyiJButton.setText("Win Innwa  File>> Zawgyi");
        winInnWaToZawgyiJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                winInnWaToZawgyiJButtonActionPerformed(evt);
            }
        });

        MessageForMS_WordJTextArea.setEditable(false);
        MessageForMS_WordJTextArea.setColumns(20);
        MessageForMS_WordJTextArea.setFont(new java.awt.Font("Zawgyi-One", 0, 13)); // NOI18N
        MessageForMS_WordJTextArea.setLineWrap(true);
        MessageForMS_WordJTextArea.setRows(5);
        MessageForMS_WordJTextArea.setText("This will convert either Zawgyi Font to Win Innwa or Win Innwa to Zawgyi Font. \nThis will convet both *.doc and *.docx file formats. \n\nဒီပရိုဂရမ္ကေန ေဇာ္ဂ်ီေဖာင့္မွ ၀င္းအင္း၀ စာလံုးကို လည္းေကာင္း၊ ၀င္းအင္းမွ ေဇာ္ဂ်ီ ျမန္မာစာ \nစာလံုးမ်ားကို တဖိုင္လံုးအလိုက္ ေျပာင္းေပးသြားမွာ ျဖစ္ပါတယ္။ ဖိုင္အမ်ဳိးအစားမ်ားမွာ *.doc နဲ႔ \n*.docx ဖိုင္ အမ်ဳိးအစား ၂ ခုစလံုးကို ေျပာင္းႏိုင္ပါတယ္။ \n");
        jScrollPane2.setViewportView(MessageForMS_WordJTextArea);

        copyRightJLabel.setText("Copyright @  Kamway Joejar. Free to use and Not For Sale.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(zawgyiToWinInnwaJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(winInnWaToZawgyiJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                        .addGap(333, 333, 333))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(copyRightJLabel)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(winInnWaToZawgyiJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(zawgyiToWinInnwaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(copyRightJLabel)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Converting by Word Files", jPanel1);

        WinInnwaJTextArea.setColumns(20);
        WinInnwaJTextArea.setFont(new java.awt.Font("Win Innwa", 0, 14)); // NOI18N
        WinInnwaJTextArea.setRows(5);
        jScrollPane3.setViewportView(WinInnwaJTextArea);

        ZawgyiJTextArea.setColumns(20);
        ZawgyiJTextArea.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ZawgyiJTextArea.setRows(5);
        jScrollPane4.setViewportView(ZawgyiJTextArea);

        winInnwaToZawgyiTextAreaJButton.setText("Win Innwa to Zawgyi ");
        winInnwaToZawgyiTextAreaJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                winInnwaToZawgyiTextAreaJButtonActionPerformed(evt);
            }
        });

        enterZawgyiFontJLabel.setFont(new java.awt.Font("Zawgyi-One", 1, 14)); // NOI18N
        enterZawgyiFontJLabel.setText("Enter Zawgyi Text Here / ေဇာ္ဂ်ီ စာလံုးကို ၀င္းအင္း၀ စာလံုးသို႔ ေျပာင္းရန္။ ");

        zawgyiToWinInnwaTextAreaJButton.setText("Zawgyi to Win Innwa");
        zawgyiToWinInnwaTextAreaJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                zawgyiToWinInnwaTextAreaJButtonActionPerformed(evt);
            }
        });

        enterWinInnwaJLabel1.setFont(new java.awt.Font("Zawgyi-One", 1, 14)); // NOI18N
        enterWinInnwaJLabel1.setText("Enter Win Innwa Text Here / ၀င္းအင္း၀ စာလံုးကို ေဇာ္ဂ်ီသို႔ ေျပာင္းရန္။ ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterZawgyiFontJLabel)
                .addGap(0, 120, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(enterWinInnwaJLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(winInnwaToZawgyiTextAreaJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(zawgyiToWinInnwaTextAreaJButton)
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterWinInnwaJLabel1)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winInnwaToZawgyiTextAreaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zawgyiToWinInnwaTextAreaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(enterZawgyiFontJLabel)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Changing by Paragraphs", jPanel2);

        jMenu1.setText("File");

        jMenuItem1.setText("File");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    public void fileFilterType ()
    {
        fileChooser = new JFileChooser(); 
        // Creating a extension filters
        FileNameExtensionFilter docxExtensionFilter = new FileNameExtensionFilter("*.docx", "docx");
        FileNameExtensionFilter docExtensionFilter = new FileNameExtensionFilter("*.doc", "doc");
        
        fileChooser.setFileFilter(docExtensionFilter);
        fileChooser.setFileFilter(docxExtensionFilter);
        
    }// end fileFilterType ()
    
    public String ReadDoc () throws FileNotFoundException, IOException
    {
        // System.out.println("ReadDOC ***************");
        
        HWPFDocument doc = new HWPFDocument(new FileInputStream (fileChooser.getSelectedFile()));
        WordExtractor extractorDoc = new WordExtractor(doc);
        // System.out.println( extractorDoc.getText()); 
        
        String word = extractorDoc.getText(); 
        // System.out.println(word);
        
        return word; 
    }
    
    public String ReadDocx () throws FileNotFoundException, IOException
    {
        XWPFDocument docx = new XWPFDocument(new FileInputStream (fileChooser.getSelectedFile()));
        XWPFWordExtractor extractor = new XWPFWordExtractor(docx);
        
        
        return extractor.getText();
    }
    
    
    
    private void zawgyiToWinInnwaJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_zawgyiToWinInnwaJButtonActionPerformed
    {//GEN-HEADEREND:event_zawgyiToWinInnwaJButtonActionPerformed
        try
        {
            
            fileFilterType ();
            // fileChooser = new JFileChooser();
            
            int value = fileChooser.showOpenDialog(null);

            // Reading a *.docx file 
            if (value == JFileChooser.APPROVE_OPTION)
            {
                // Getting a document file
                String fileType = fileChooser.getFileFilter().getDescription(); 
                System.out.println(">> " + fileType);
                
                if (fileType.equals("*.doc"))
                {
                    System.out.println(">>>" + ReadDoc());
                    zwToInnwa.zawgyiToWinInnwa(ReadDoc());
                }
                
                if (fileType.equals("*.docx"))
                {
                    // Calling the ZawgyiTOWinInnawa Instance 
                    zwToInnwa.zawgyiToWinInnwa(ReadDocx());
                    
                }
                
                

            }// end if
        }
        catch (Exception e)
        {

        }
    }//GEN-LAST:event_zawgyiToWinInnwaJButtonActionPerformed

   
    
    private void winInnWaToZawgyiJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_winInnWaToZawgyiJButtonActionPerformed
    {//GEN-HEADEREND:event_winInnWaToZawgyiJButtonActionPerformed
        
        try
        {
            
            fileFilterType ();
            
            int value = fileChooser.showOpenDialog(null);

            // Reading a *.docx file 
            if (value == JFileChooser.APPROVE_OPTION)
            {
                // Getting a document file
                String fileType = fileChooser.getFileFilter().getDescription(); 
                // System.out.println(">> " + fileName);
                
                if (fileType.equals("*.docx"))
                {
                    // Calling the ZawgyiTOWinInnawa Instance 
                    winInnwaToZawgyi.winInnwaToZawgyi(ReadDocx());

                }
                
                if (fileType.equals("*.doc"))
                {
                    
                    // Calling the ZawgyiTOWinInnawa Instance 
                    winInnwaToZawgyi.winInnwaToZawgyi(ReadDoc());
                    
                }

            }// end if
        }
        catch (Exception e)
        {

        }
        /*
        
        try
        {
            fileFilterType (); 

            int value = fileChooser.showOpenDialog(null);

            // Reading a *.docx file 
            if (value == JFileChooser.APPROVE_OPTION)
            {
                // Getting a document file
                String fileName = fileChooser.getSelectedFile().getName();
                // System.out.println(">> " + fileName);
                
                if (fileName.contains(".docx"))
                {
                    // Calling the ZawgyiTOWinInnawa Instance 
                    winInnwaToZawgyi.winInnwaToZawgyi(ReadDocx(), this.winInnWaToZawgyiJButton);
                    
                }
                
                if (fileName.contains(".doc"))
                {
                    // Calling the ZawgyiTOWinInnawa Instance 
                    winInnwaToZawgyi.winInnwaToZawgyi(ReadDoc (), this.winInnWaToZawgyiJButton);
                    
                }

            }// end if
            
            
        }
        catch (Exception e)
        {

        }
        */
    }//GEN-LAST:event_winInnWaToZawgyiJButtonActionPerformed

    private void winInnwaToZawgyiTextAreaJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_winInnwaToZawgyiTextAreaJButtonActionPerformed
    {//GEN-HEADEREND:event_winInnwaToZawgyiTextAreaJButtonActionPerformed
        
        
        
        // Clearing the Text Area 
        ZawgyiJTextArea.setText("\u1005\u1004\u103a\u1039");
        
      /*
        // TO DO -- Need to set the cursor position
        String words = WinInnwaJTextArea.getText();
        
        
        char ch; 
        
        for (int i = 0; i < words.length(); i++)
        {
            ch = words.charAt(i); 
            ZawgyiJTextArea.append(Character.toString(winInnwaToZawgyi.WordToChar(ch)));
        }
        */
        
    }//GEN-LAST:event_winInnwaToZawgyiTextAreaJButtonActionPerformed

    private void zawgyiToWinInnwaTextAreaJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_zawgyiToWinInnwaTextAreaJButtonActionPerformed
    {//GEN-HEADEREND:event_zawgyiToWinInnwaTextAreaJButtonActionPerformed
        // Clearing the Text Area 
        WinInnwaJTextArea.setText("");
        
       
        // TO DO -- Need to set the cursor position
        String words = ZawgyiJTextArea.getText();
        char ch; 
        
        for (int i = 0; i < words.length(); i++)
        {
            ch = words.charAt(i); 
            // WinInnwaJTextArea.append(Character.toString(zwToInnwa.WordToChar(ch)));
            WinInnwaJTextArea.append(zwToInnwa.WordToChar(ch));
        }
            
       
    }//GEN-LAST:event_zawgyiToWinInnwaTextAreaJButtonActionPerformed

    
   
  
    /**
     @param args the command line arguments
     */
    public static void main (String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
           
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
//                if ("Nimbus".equals(info.getName()))
//                {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                  
                // Window Look 
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
               
            }
           
           
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ZawgyiToWinInnwaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ZawgyiToWinInnwaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ZawgyiToWinInnwaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ZawgyiToWinInnwaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
            java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run ()
                {
                    new ZawgyiToWinInnwaGUI().setVisible(true);
                }
            });
        
        */
        java.awt.EventQueue.invokeLater(() ->
        {
            new ZawgyiToWinInnwaGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea MessageForMS_WordJTextArea;
    private javax.swing.JTextArea WinInnwaJTextArea;
    private javax.swing.JTextArea ZawgyiJTextArea;
    private javax.swing.JLabel copyRightJLabel;
    private javax.swing.JLabel enterWinInnwaJLabel1;
    private javax.swing.JLabel enterZawgyiFontJLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton winInnWaToZawgyiJButton;
    private javax.swing.JButton winInnwaToZawgyiTextAreaJButton;
    private javax.swing.JButton zawgyiToWinInnwaJButton;
    private javax.swing.JButton zawgyiToWinInnwaTextAreaJButton;
    // End of variables declaration//GEN-END:variables
}
